name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt-get update
        sudo apt-get install haskell-platform
        sudo apt-get install perl6
        sudo apt-get install ruby
        wget https://github.com/emojicode/emojicode/releases/download/v1.0-beta.1/Emojicode-1.0-beta.1-Linux-x86_64.tar.gz -O emojicode.tar.gz \
        && tar -xzf emojicode.tar.gz && rm emojicode.tar.gz \
        && cd Emojicode-1.0-beta.1-Linux-x86_64 && ./install.sh \
        && cd .. && rm -r Emojicode-1.0-beta.1-Linux-x86_64
        emojicodec fizzbuzz.emojic -o emojifizz
        gcc -std=gnu99 fizzbuzz.c -o cfizz
        javac fizzbuzz.java
        ./cfizz | diff fizzbuzz.txt -
        python3 fizzbuzz.py | diff fizzbuzz.txt -
        node fizzbuzz.js | diff fizzbuzz.txt -
        bash fizzbuzz.sh | diff fizzbuzz.txt -
        java fizzbuzz | diff fizzbuzz.txt -
        go run fizzbuzz.go | diff fizzbuzz.txt -
        ruby fizzbuzz.rb | diff fizzbuzz.txt - 
        perl6 fizzbuzz.p6 | diff fizzbuzz.txt -
        runhaskell fizzbuzz.hs | diff fizzbuzz.txt -
        ./emojifizz | diff fizzbuzz.txt -
